services:
  main-app:  
    env_file:
      - ./.env
    
    build:
      dockerfile: Dockerfile_ml_service

    ports:
      - "${APP_PORT}:${APP_PORT}"
    
    hostname: main_app
    
    volumes:
      - type: bind
        source: ./models
        target: /app/models

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    hostname: prometheus

  grafana:
      image: grafana/grafana
      env_file:
      - ./.env
      ports:
      - 3000:3000
      environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}